name: Update data

on:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *' # Every hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Run update
        run: yarn && yarn build && yarn start
        working-directory: ./scripts
        timeout-minutes: 30
        env:
          POOL_ID: "pool1kchver88u3kygsak8wgll7htr8uxn5v35lfrsyy842nkscrzyvj"
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/public/cardano/data
          git commit -m "Updated data"
          git pull --rebase
          git push
